Feature/lista platillos
Eimvi/AlioliFood-Angular-UNISTMO pull request #15
Opened 2022-06-03 16:00 UTC by MarioBasilio08

1. Se creo la estructura de las tarjetas de platillos con sus estilos
![image](https://user-images.githubusercontent.com/90487768/171900982-37ff804d-a377-4cda-aa65-7dbd607e2118.png)

2. Se creo funciones para recuperas las variables de orden y cantidad del local storage
![image](https://user-images.githubusercontent.com/90487768/171901291-509558d4-e2ff-4b1b-a789-41475fa4bbb5.png)

3. En el ngOnInit  se recupera la información de la orden
![image](https://user-images.githubusercontent.com/90487768/171901400-2e1bf834-b37f-4d3b-a0e0-a701738dd952.png)

4. Para sumar o restar se realiza la búsqueda del item correcto, se aplica la operación y se actualiza la orden en el local storage, de igual forma se realiza un emit de la orden para que otros componentes tengan la información actualizada
![image](https://user-images.githubusercontent.com/90487768/171901703-85a1be69-29e4-4450-8aca-678c39abe83b.png)

5.Para eliminar una tarjeta por completo se realiza un filtrado excluyendo el item que se borrado, se actualiza la orden y se realiza un emit
![image](https://user-images.githubusercontent.com/90487768/171901999-f9963952-2d8a-446a-8dca-b93e4e24c951.png)

6.Provisionalmente se instancio el componentes en ver-pedidos, el compañero a cargo de la historia resumen pedido, subirá la etiqueta correcta para el uso del paso de valores de padre a hijo
![image](https://user-images.githubusercontent.com/90487768/171902225-5f23f870-6af8-444e-bde5-2601d0a7a592.png)

2022-06-03 16:02 UTC, MarioBasilio08 commented
Por favor omitir el primer commit Estructura y estilos tarjeta platillos, fue un error al seleccionar lo que se subiría, eso forma parte de la rama platillos_fix

2022-06-03 17:44 UTC, Eimvi commented
> Por favor omitir el primer commit Estructura y estilos tarjeta platillos, fue un error al seleccionar lo que se subiría, eso forma parte de la rama platillos_fix

No puedo omitir tu commit, ese commit es el que genera error de fusión en los archivos

2022-06-03 17:47 UTC, Eimvi requested changes

2022-06-03 17:47 UTC, Eimvi commented on src/app/ver-pedidos/components/lista-platillos/lista-platillos.component.ts
> +    //this.enviarOrden.emit(this.pedidoOrdenado)
Borra esta línea de código si no la ocupas, si otro compañero la ocupará después debes dejarla descomentada

2022-06-03 17:47 UTC, Eimvi commented on src/app/ver-pedidos/ver-pedidos.component.html
> +  <!-- <app-lista-platillos (enviarOrden)="pedidoOrdenado=($event)"></app-lista-platillos> -->
Borra esta línea de código si no la ocupas, si otro compañero la ocupará después debes dejarla descomentada y borrar la primera línea sin el Output

2022-06-05 01:20 UTC, Eimvi requested changes

2022-06-05 01:20 UTC, Eimvi commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Porqué tienes MenuRoutingModule acá en Shared?

2022-06-05 02:01 UTC, MarioBasilio08 commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Ese import me está permitiendo que el navbar funcione, ya que si se lo quito aparece las opciones como texto plano, lo que le comente

2022-06-05 03:00 UTC, Eimvi commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Ya les había comentado en una reunión que necesitan un Módulo FormsModule. Eso que implementas no está bien.

2022-06-05 03:02 UTC, MarioBasilio08 commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Si lo intente implementar también pero no funcionó y buscando en foros encontre esa solución

2022-06-05 03:03 UTC, MarioBasilio08 commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Funcionó*

2022-06-05 03:18 UTC, Eimvi commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Entiendo, me hubieses avisado, intenta con RouterModule

2022-06-05 17:42 UTC, MarioBasilio08 commented on src/app/shared/shared.module.ts
> +import { MenuRoutingModule } from '../menu/menu-routing.module';
Hice la prueba con RouterModule y funciono, ya realice el cambio

2022-06-05 18:07 UTC, Eimvi commented
Tienes conflictos en tu PR debido a una reciente implementación de uno de tus compañeros.

2022-06-05 18:41 UTC, merged