Feature/vista previa pedido
Eimvi/AlioliFood-Angular-UNISTMO pull request #17
Opened 2022-06-04 02:37 UTC by Samuel200028

En este caso solo se agrego la vista previo pedido con el total de los platos seleccionados o elegidos por el usuario y la cuenta total de su pedido previo.

![image](https://user-images.githubusercontent.com/104949621/171974808-8fa0f2af-6368-4e7c-9999-533a7a41c967.png)

Al agregar un platillo se actualiza el numero de platos y el total. Si se actualiza la pagina obtiene el numero de platillos antes guardados en el local storage.

![image](https://user-images.githubusercontent.com/104949621/171974827-29ce62a5-baf2-4da5-9ef5-a24d72e9a377.png)

2022-06-04 15:49 UTC, Eimvi requested changes

2022-06-04 15:49 UTC, Eimvi commented on src/app/menu/components/vista-pedido/vista-pedido.component.scss
> +  //margin-bottom: 10px;
Si no lo ocupas, bórralo.

2022-06-04 15:49 UTC, Eimvi commented on src/app/menu/components/vista-pedido/vista-pedido.component.ts
> +    this.sumPlatos=0;
No entiendo, si recibes del padre la sumPlatos y sumTotal porqué acá vuelves a calcularlo?

2022-06-04 15:49 UTC, Eimvi commented on src/app/menu/components/vista-pedido/vista-pedido.component.ts
> +    console.log(this.auxPedido);
Borra tus console.log()

2022-06-07 01:45 UTC, Samuel200028 commented
cambios resueltos

2022-06-07 15:36 UTC, merged